swagger: "2.0"
host: "localhost:8000"
basePath: "/cgi-bin/cgicalc.py"
info:
  title: "Calculator"
  description: "Simple calculator"
  version: "1.0.0"
schemes:
- "http"
paths:
  /amount:
    post:
      tags:
      - "amount"
      summary: "Find the sum of numbers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "num"
        in: "query"
        description: "Add a number to the expression"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Input is ok"
          schema: 
            $ref: "#/definitions/Amount"
        405:
          description: "Invalid input"
  /difference:
    post:
      tags:
      - "difference"
      summary: "Find the difference of numbers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "num"
        in: "query"
        description: "Add a number to the expression"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Input is ok"
          schema: 
            $ref: "#/definitions/Difference"    
        405:
          description: "Invalid input"
  /multiplication:
    post:
      tags:
      - "multiplication"
      summary: "Find the multiplication of numbers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "num"
        in: "query"
        description: "Add a number to the expression"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Input is ok"
          schema: 
            $ref: "#/definitions/Multiplication"    
        405:
          description: "Invalid input"
  /division:
    post:
      tags:
      - "division"
      summary: "Find the result of dividing the numbers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "num"
        in: "query"
        description: "Add a number to the expression"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Input is ok"
          schema: 
            $ref: "#/definitions/Division"  
        405:
          description: "Invalid input"
definitions:
  Amount:
    type: "object"
    properties:
      num:
        type: "integer"
        format: "int64"
      result:
        type: "object"
        properties:
          num:
            type: "integer"
          operator:
            type: "string"
  Difference:
    type: "object"
    properties:
      num:
        type: "integer"
      result:
        type: "object"
        properties:
          num:
            type: "integer"
          operator:
            type: "string"
  Multiplication:
    type: "object"
    properties:
      num:
        type: "integer"
      result:
        type: "object"
        properties:
          num:
            type: "integer"
          operator:
            type: "string"   
  Division:
    type: "object"
    properties:
      num:
        type: "integer"
      result:
        type: "object"
        properties:
          num:
            type: "integer"
          operator:
            type: "string"
  